trigger:
- devops

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command : build
    projects: '**/*API/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*wis_unit.tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
